### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by jjz** [jsix/go2o#10]
# go2o/src/core/infrastructure/domain
src/core/infrastructure/domain/generator.go:73: undefined: util.RandInt
# go2o/src/x/echox
src/x/echox/echo.go:66: cannot use ctx.Response() (type engine.Response) as type http.ResponseWriter in argument to session.Default:
	engine.Response does not implement http.ResponseWriter (wrong type for Header method)
		have Header() engine.Header
		want Header() http.Header
src/x/echox/echo.go:66: http.Request.Body is a field, not a method
src/x/echox/echo.go:66: cannot use ctx.Request() (type engine.Request) as type *http.Request in argument to session.Default
src/x/echox/echo.go:68: unknown Context field 'Context' in struct literal
src/x/echox/echo.go:82: cannot use this.parseHandler(h) (type func(echo.Context) error) as type echo.Handler in argument to this.Echo.Get:
	func(echo.Context) error does not implement echo.Handler (missing Handle method)
src/x/echox/echo.go:87: cannot use this.parseHandler(h) (type func(echo.Context) error) as type echo.Handler in argument to this.Echo.Any:
	func(echo.Context) error does not implement echo.Handler (missing Handle method)
src/x/echox/echo.go:92: cannot use this.parseHandler(h) (type func(echo.Context) error) as type echo.Handler in argument to this.Echo.Post:
	func(echo.Context) error does not implement echo.Handler (missing Handle method)
src/x/echox/echo.go:98: ctx.Param undefined (type *Context has no field or method Param)
src/x/echox/render.go:24: cannot use new(GoTemplateForEcho) (type *GoTemplateForEcho) as type echo.Renderer in assignment:
	*GoTemplateForEcho does not implement echo.Renderer (wrong type for Render method)
		have Render(io.Writer, string, interface {}) error
		want Render(io.Writer, string, interface {}, echo.Context) error
src/x/echox/echo.go:98: too many errors

**Comment by jsix** [comment]
请更新gof 和echo的库。
go get -u github.com/jsix/gof
go get -u github.com/labstatck/echo

**Comment by jjz** [comment]
go get -u github.com/jsix/gof
go get  -u github.com/labstack/echo/ 是这个库吧。已经更新到最新了，但是还是报上面的错误

**Comment by jsix** [comment]
抱歉，引用错误了
https://github.com/jsix/go2o/commit/43e56b781d369c79e4bef7230a51111a86f66ff0

**Comment by jjz** [comment]
src/x/echox/echo.go:33: embedded type cannot be a pointer to interface 这个错误还是有的，库都是最新的

**Comment by jsix** [comment]
我用了最新的golang版本，是否是这问题引起的？

**Comment by jjz** [comment]
我的是1.6版本
