### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by daotianya** [jsix/go2o#28]
source code tag: 0.11

apples-MacBook-Pro:go2o carlos$ go build go2o-serve.go 
# go2o/src/core/query
src/core/query/partner_query.go:21: undefined: gof.Storage
# go2o/src/app/util
src/app/util/member.go:22: undefined: gof.Storage
src/app/util/member.go:34: undefined: gof.Storage
src/app/util/member.go:47: undefined: gof.Storage
src/app/util/member.go:59: undefined: gof.Storage
src/app/util/member.go:71: undefined: gof.Storage
# go2o/src/core
src/core/app.go:32: undefined: gof.Storage
apples-MacBook-Pro:go2o carlos$ 

是否是因为"github.com/jsix/gof"下的包内容改了，

我有几个疑问，

1：如果使用0.12逻辑部分代码；界面部分是否能平衡迁移0.11?

**Comment by jsix** [comment]
是的，gof改过了。 改成storage.Interface{}

**Comment by daotianya** [comment]
gof.Storage 之前是做什么用呢？ 改成storage.Interface{}后怎么调用？直接替换gof？

**Comment by jsix** [comment]
接口定义大致一样
